'^/wp-admin$':
  to: "/wp/wp-admin/"
  regexp: true
'^/wp-admin/(.*)':
  to: "/wp/wp-admin/$1"
  regexp: true
'^/colby-magazine/?$':
  to: 'https://magazine.colby.edu/'
  regexp: true
  code: 301
'^/oyster/?$':
  to: 'https://www.youtube.com/watch?v=FzYVovKafZI'
  regexp: true
  code: 301